# See [Connector Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/connector-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-stock-ticker-api:dev
acceptance_tests:
  basic_read:
    tests:
      - config_path: secrets/valid_config.json
        configured_catalog_path: fullrefresh_configured_catalog.json
        empty_streams: []
  connection:
    tests:
      - config_path: secrets/valid_config.json
        status: succeed
      - config_path: secrets/invalid_config.json
        status: failed
  discovery:
    tests:
      - config_path: secrets/valid_config.json
  full_refresh:
    tests:
      - config_path: secrets/valid_config.json
        configured_catalog_path: fullrefresh_configured_catalog.json
  spec:
    tests:
      - config_path: secrets/valid_config.json
        spec_path: spec.json
  # incremental:
  #   bypass_reason: "This connector does not implement incremental sync"
